user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /user

product:
    resource: "@ProductBundle/Resources/config/routing.xml"
    prefix:   /product

category:
    resource: "@CategoryBundle/Resources/config/routing.xml"
    prefix:   /category

app:
    resource: "@AppBundle/Resources/config/routing.xml"
    prefix:   /
